spring:
  application:
    name: ERP application
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp?useSSL=false
    password: admin
    username: root
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect
  jpa:
    hibernate:
      ddl-auto: create