spring:
  application:
    name: ERP application
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/erp?useSSL=false
    password: root
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQLDialect

